// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using NakhlaBelal.DataAccess;

#nullable disable

namespace NakhlaBelal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260420000000_AddNotifications")]
    partial class AddNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder)
        {
            // Intentionally left minimal.
            // Snapshot is maintained by ApplicationDbContextModelSnapshot; this migration uses raw SQL.
        }
    }
}
